
services:
  db:
    image: mysql:8.0
    restart: "no"
    volumes:
    - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: notes_app
      MYSQL_USER: notes
      MYSQL_PASSWORD: notes
    networks:
    - notes

  app:
    depends_on:
    - db
    build: 
      context: .
      dockerfile: Dockerfile
    restart: "no"
    volumes:
      - "./:/var/www/html"
    ports:
    - 80:80
    networks:
    - notes

  pma:
    depends_on:
    - db
    image: phpmyadmin/phpmyadmin
    restart: "no"
    ports:
    - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    networks:
    - notes

networks:
  notes:

volumes:
  data:
